### ISSUE TITLE
how to modify  the  config.yaml  in full node 

### ISSUE THREAD

**Issue by yuzhongrong** [Flofie/chia-desktop#4]
If your Wallet is not running on the same machine as chia-desktop then change the configuration in config.yaml self_hostname to the internal IP-Address (e.g. 192.168.2.100) of your Wallet

**Comment by yuzhongrong** [comment]
The desktop is at 192.168.3.200, and all upstream services are at 192.168.3.202
How to modify config.yaml

**Comment by yuzhongrong** [comment]
The desktop is at 192.168.3.200, and all upstream services are at 192.168.3.202
How to modify config.yaml

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/117546558-94cf6900-b05d-11eb-860c-d40672fff420.png)


Don't understand how to modify config.yaml

**Comment by yuzhongrong** [comment]
how to modify  in full node machine of 192.168.3.202   
![image](https://user-images.githubusercontent.com/7382234/117547000-d06b3280-b05f-11eb-95eb-7fb494dd9c1f.png)
connection refused  from 192.168.3.200 to 192.168.3.202

**Comment by yuzhongrong** [comment]
[ipfsnets@localhost ~]$ telnet 192.168.3.202 9256
Trying 192.168.3.202...
telnet: connect to address 192.168.3.202: Connection refused

telnet is not ok

**Comment by yuzhongrong** [comment]
my chia-desktop  server in 192.168.3.200

**Comment by Flofie** [comment]
On which machine is your wallet running? 192.168.3.202? Then you need to change the config.yml on 192.168.3.202 so that it binds to your ip address and not to localhost - therfore change the binding in config from **self_hostname: localhost** to **self_hostname: 192.168.3.202**
Then you should be able to connect from the other machine where chia-desktop is running.

**Comment by yuzhongrong** [comment]
没有这个字段

**Comment by yuzhongrong** [comment]
在config.yaml 没有这个字段 self_hostname 到底代表什么

**Comment by yuzhongrong** [comment]
钱包运行在192.168.3.202  但是config.yaml中没有 这个self_hostname字段

**Comment by Flofie** [comment]
sorry I dont understand
